# cloudbuild.yaml
steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/enrichment-service:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile.prod'
      - '.'
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/enrichment-service:$COMMIT_SHA']
  
  # Deploy API to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'enrichment-api'
      - '--image=gcr.io/$PROJECT_ID/enrichment-service:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=2'
      - '--max-instances=100'
      - '--set-env-vars'
      - 'SERVICE_MODE=api,ENVIRONMENT=prod'
  
  # Deploy Worker to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'enrichment-worker'
      - '--image=gcr.io/$PROJECT_ID/enrichment-service:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--min-instances=5'
      - '--max-instances=50'
      - '--set-env-vars'
      - 'SERVICE_MODE=worker,ENVIRONMENT=prod'